directory: ~/Music/music
library: ~/.config/beets/musiclibrary.db
plugins: fromfilename discogs fetchart lastgenre acousticbrainz badfiles missing edit chroma filetote inline mpdupdate thumbnails lastimport keyfinder
paths:
    default: artists/$albumartist/$albumartist - $year - $album %if{$catalognum,[$catalognum]} %aunique{albumartist album, albumtype label format albumdisambig releasegroupdisambig, []} ($filetype)/%if{$multidisc,$disc-}$track - $title
    singleton: singletons/$artist - $year - $title (from $album) %if{$catalognum,[$catalognum]} ($filetype)
    comp: compilations/VA ($label) - $year - $album %if{$catalognum,[$catalognum]} %aunique{albumartist album, albumtype label format albumdisambig releasegroupdisambig, []} ($filetype)/%if{$multidisc,$disc-}$track - $title
discogs:
   source_weight: 0.75
lastfm:
    user: cklamra
badfiles:
    check_on_import: no
    commands:
        ogg: myoggchecker --opt1 --opt2
        flac: flac --test --warnings-as-errors --silent
edit:
  itemfields: catalognum media disc track title artist album 
musicbrainz:
    extra_tags: [media, year, label, catalognum, country] 
filetote:
  extensions: .cue .log .png .jpeg .nfo .jpg .JPG .JPEG .txt
item_fields:
    filetype: format + str(bitrate).strip('kbps') if format == 'MP3' else format
keyfinder:
    auto: yes
    bin: keyfinder-cli
